/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface IntroBountyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bounties"
      | "cancelBounty"
      | "createBounty"
      | "nextBountyId"
      | "releaseBounty"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BountyCancelled"
      | "BountyCreated"
      | "BountyReleased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "bounties",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelBounty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createBounty",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "nextBountyId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "releaseBounty",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "bounties", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextBountyId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseBounty",
    data: BytesLike
  ): Result;
}

export namespace BountyCancelledEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    creator: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [bountyId: bigint, creator: string, amount: bigint];
  export interface OutputObject {
    bountyId: bigint;
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyCreatedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    creator: AddressLike,
    targetId: string,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    bountyId: bigint,
    creator: string,
    targetId: string,
    amount: bigint
  ];
  export interface OutputObject {
    bountyId: bigint;
    creator: string;
    targetId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyReleasedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    introducer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    bountyId: bigint,
    introducer: string,
    amount: bigint
  ];
  export interface OutputObject {
    bountyId: bigint;
    introducer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IntroBounty extends BaseContract {
  connect(runner?: ContractRunner | null): IntroBounty;
  waitForDeployment(): Promise<this>;

  interface: IntroBountyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bounties: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        creator: string;
        targetId: string;
        amount: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  cancelBounty: TypedContractMethod<
    [_bountyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createBounty: TypedContractMethod<[_targetId: string], [bigint], "payable">;

  nextBountyId: TypedContractMethod<[], [bigint], "view">;

  releaseBounty: TypedContractMethod<
    [_bountyId: BigNumberish, _introducer: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bounties"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        creator: string;
        targetId: string;
        amount: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelBounty"
  ): TypedContractMethod<[_bountyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createBounty"
  ): TypedContractMethod<[_targetId: string], [bigint], "payable">;
  getFunction(
    nameOrSignature: "nextBountyId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "releaseBounty"
  ): TypedContractMethod<
    [_bountyId: BigNumberish, _introducer: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BountyCancelled"
  ): TypedContractEvent<
    BountyCancelledEvent.InputTuple,
    BountyCancelledEvent.OutputTuple,
    BountyCancelledEvent.OutputObject
  >;
  getEvent(
    key: "BountyCreated"
  ): TypedContractEvent<
    BountyCreatedEvent.InputTuple,
    BountyCreatedEvent.OutputTuple,
    BountyCreatedEvent.OutputObject
  >;
  getEvent(
    key: "BountyReleased"
  ): TypedContractEvent<
    BountyReleasedEvent.InputTuple,
    BountyReleasedEvent.OutputTuple,
    BountyReleasedEvent.OutputObject
  >;

  filters: {
    "BountyCancelled(uint256,address,uint256)": TypedContractEvent<
      BountyCancelledEvent.InputTuple,
      BountyCancelledEvent.OutputTuple,
      BountyCancelledEvent.OutputObject
    >;
    BountyCancelled: TypedContractEvent<
      BountyCancelledEvent.InputTuple,
      BountyCancelledEvent.OutputTuple,
      BountyCancelledEvent.OutputObject
    >;

    "BountyCreated(uint256,address,string,uint256)": TypedContractEvent<
      BountyCreatedEvent.InputTuple,
      BountyCreatedEvent.OutputTuple,
      BountyCreatedEvent.OutputObject
    >;
    BountyCreated: TypedContractEvent<
      BountyCreatedEvent.InputTuple,
      BountyCreatedEvent.OutputTuple,
      BountyCreatedEvent.OutputObject
    >;

    "BountyReleased(uint256,address,uint256)": TypedContractEvent<
      BountyReleasedEvent.InputTuple,
      BountyReleasedEvent.OutputTuple,
      BountyReleasedEvent.OutputObject
    >;
    BountyReleased: TypedContractEvent<
      BountyReleasedEvent.InputTuple,
      BountyReleasedEvent.OutputTuple,
      BountyReleasedEvent.OutputObject
    >;
  };
}
